name: Release
on:
  push:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build-cli:
    strategy:
      matrix:
        include:
        - arch: linux-amd64
          runs-on: ubuntu-24.04
        - arch: linux-arm64
          runs-on: ubuntu-24.04-arm
        - arch: macos-amd64
          runs-on: macos-15-intel
        - arch: macos-arm64
          runs-on: macos-15
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      
      - name: Install just
        uses: extractions/setup-just@v1
      
      - name: Build
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          just build
          mkdir bin
          mv target/release/pruner bin/pruner-${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: pruner-${{ matrix.arch }}
          if-no-files-found: error
          path: bin/pruner-${{ matrix.arch }}

  release-cli:
    runs-on: ubuntu-24.04
    needs: [build-cli]
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
    steps:
      - uses: actions/checkout@v4

      - name: Download Binary Artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: pruner-*
          path: bin

      - name: Calculate checksums
        run: |
          for file in bin/*; do
            shasum -a 256 "$file" >> checksums.txt
          done

          mv checksums.txt bin/checksums.txt

      - name: Copy WIT
        run: |
          cp wit/world.wit bin/plugin-api.wit

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          files: |
            bin/*
